import Phaser from 'phaser';

/**
 * BootScene — First scene loaded. Handles asset preloading.
 * Shows a loading bar, then transitions to MenuScene.
 */
export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: 'BootScene' });
  }

  preload(): void {
    // Loading bar
    const { width, height } = this.cameras.main;
    const barWidth = 320;
    const barHeight = 20;
    const barX = (width - barWidth) / 2;
    const barY = height / 2;

    const bg = this.add.rectangle(width / 2, barY, barWidth, barHeight, 0x222222);
    bg.setStrokeStyle(2, 0x444444);

    const fill = this.add.rectangle(barX + 2, barY, 0, barHeight - 4, 0x2563EB);
    fill.setOrigin(0, 0.5);

    const titleText = this.add.text(width / 2, barY - 50, 'COMMAND & CONQUER: NEW ORDER', {
      fontFamily: 'monospace',
      fontSize: '20px',
      color: '#60A5FA',
    }).setOrigin(0.5);

    const loadingText = this.add.text(width / 2, barY + 30, 'Loading...', {
      fontFamily: 'monospace',
      fontSize: '14px',
      color: '#9CA3AF',
    }).setOrigin(0.5);

    this.load.on('progress', (value: number) => {
      fill.width = (barWidth - 4) * value;
    });

    this.load.on('complete', () => {
      titleText.destroy();
      loadingText.destroy();
      bg.destroy();
      fill.destroy();
    });

    // Load game atlas (generated by tools/generate-sprites.ts)
    this.load.atlas('game-atlas', 'assets/sprites/game-atlas.png', 'assets/sprites/game-atlas.json');
  }

  create(): void {
    this.scene.start('MenuScene');
  }
}
